---
abstract: 'Strip unwanted HTML tags and attributes'
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires:
  Module::Build: '0.28'
  Test::Fatal: '0'
  Test::More: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Restrict
no_index:
  directory:
    - t
    - xt
    - examples
requires:
  Carp: '0'
  Data::Dump: '0'
  HTML::Entities: '0'
  HTML::Parser: '0'
  List::MoreUtils: '0'
  Moo: '1.002000'
  Scalar::Util: '0'
  Sub::Quote: '0'
  Type::Tiny: '1.000001'
  Types::Standard: '0'
  URI: '0'
  namespace::clean: '0'
  perl: '5.006'
  strict: '0'
resources:
  bugtracker: http://github.com/oalders/html-restrict/issues
  homepage: https://github.com/oalders/html-restrict
  repository: https://github.com/oalders/html-restrict.git
version: 2.2.2
x_contributors:
  - "Arthur Axel 'fREW' Schmidt <frioux@gmail.com>"
  - 'David Golden <dagolden@cpan.org>'
  - 'Fitz Elliott <fitz.elliott@gmail.com>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'Graham TerMarsch <graham@howlingfrog.com>'
  - 'Mark Jubenville <mark@raybec.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'perlpong <calyx238@gmail.com>'
  - 'skaufman <sam@socialflow.com>'
